import HigherRankSyntax.Typing.Telescope

/-!
# The judgements

Seven judgements over an ambient, which need not itself be well formed, defined
by one simultaneous induction: an expression is well formed, two expressions
are equal, two boundaries are equal, a substitution fills a telescope, two
substitutions agree as fillings of a telescope, a declaration is well formed,
and a telescope is well formed.  Filling a telescope runs over its slots in
order: the first slot's filler is checked against the boundary that slot
declares, over the ambient extended by the entries it binds, and is then
substituted into the slots that follow.

Also here: the slot-by-slot description of fillings and of their agreement,
fillings of concatenated telescopes, symmetry and transitivity of equality of
boundaries, equality of telescopes over one ambient or over two, and
well-formedness of ambients.
-/

mutual

/-- An expression `.ap x args` over an ambient is well formed when the
declaration of `x` is not an equation and `args` fills the telescope of entries
`x` binds. -/
inductive Wf_e : {Δ : C.Arity} → Ambient Δ → Expr Δ → Prop where
  | ap {Δ : C.Arity} {Ξ : Ambient Δ} {α : C.Arity} (x : Δ ∋ α) (args : Subst α Δ)
      (head : ¬ (Ξ.declaration x).isEq)
      (fill : Wf_s Ξ (Ξ.binding x) args) :
      Wf_e Ξ (.ap x args)

/-- Equality of expressions over an ambient, generated by: reflexivity on
well-formed expressions; symmetry; transitivity; each equation `.eq l r`
declared by a slot of the ambient, with `l` and `r` well formed, instantiated by
a filling of the entries that slot binds; and substitution of agreeing fillings
of a well-formed telescope into expressions equal over the extended ambient. -/
inductive Eq_e : {Δ : C.Arity} → Ambient Δ → Expr Δ → Expr Δ → Prop where
  | refl {Δ : C.Arity} {Ξ : Ambient Δ} {e : Expr Δ} (h : Wf_e Ξ e) : Eq_e Ξ e e
  | symm {Δ : C.Arity} {Ξ : Ambient Δ} {e e' : Expr Δ} (h : Eq_e Ξ e e') : Eq_e Ξ e' e
  | trans {Δ : C.Arity} {Ξ : Ambient Δ} {e e' e'' : Expr Δ}
      (h : Eq_e Ξ e e') (h' : Eq_e Ξ e' e'') : Eq_e Ξ e e''
  | hyp {Δ : C.Arity} {Ξ : Ambient Δ} {Λ : C.Arity} (q : Δ ∋ Λ) (l r : Expr (Δ ⋈ Λ))
      (args : Subst Λ Δ)
      (decl : Ξ.declaration q = .eq l r)
      (hl : Wf_e (Ξ ⋈ Ξ.binding q) l)
      (hr : Wf_e (Ξ ⋈ Ξ.binding q) r)
      (fill : Wf_s Ξ (Ξ.binding q) args) :
      Eq_e Ξ (args ⋆ l) (args ⋆ r)
  | congr {Δ Ω : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Ω} {e e' : Expr (Δ ⋈ Ω)}
      (σ θ : Subst Ω Δ) (hΘ : Wf_t Ξ Θ) (hσ : Wf_s Ξ Θ σ) (hθ : Wf_s Ξ Θ θ)
      (agree : Eq_s Ξ Θ σ θ) (h : Eq_e (Ξ ⋈ Θ) e e') :
      Eq_e Ξ (σ ⋆ e) (θ ⋆ e')

/-- Two boundaries over an ambient are equal when both are `sort`, both are
`of` equal expressions, or both are equations with equal left and equal right
sides. -/
inductive Eq_bd : {Δ : C.Arity} → Ambient Δ → Bd Δ → Bd Δ → Prop where
  | sort {Δ : C.Arity} {Ξ : Ambient Δ} : Eq_bd Ξ .sort .sort
  | of {Δ : C.Arity} {Ξ : Ambient Δ} {S S' : Expr Δ} (h : Eq_e Ξ S S') :
      Eq_bd Ξ (.of S) (.of S')
  | eq {Δ : C.Arity} {Ξ : Ambient Δ} {l r l' r' : Expr Δ}
      (hl : Eq_e Ξ l l') (hr : Eq_e Ξ r r') : Eq_bd Ξ (.eq l r) (.eq l' r')

/-- A substitution fills a telescope over an ambient `Ξ`: every substitution
fills `.nil`, and `σ` fills `dTel.cons bind boundary rest` when, over `Ξ ⋈ bind`,
`boundary` has equal sides if it is an equation, and otherwise the first filler
is well formed with computed boundary equal to `boundary`; and the remaining
fillers fill `rest` instantiated by the first filler. -/
inductive Wf_s : {Δ Ω : C.Arity} → Ambient Δ → dTel Δ Ω → Subst Ω Δ → Prop where
  | nil {Δ : C.Arity} {Ξ : Ambient Δ} {σ : Subst 1 Δ} : Wf_s Ξ .nil σ
  | cons {Δ α Ω : C.Arity} {Ξ : Ambient Δ} {bind : dTel Δ α} {boundary : Bd (Δ ⋈ α)}
      {rest : dTel (Δ ⋈ C.single α) Ω} {σ : Subst (C.single α ⋈ Ω) Δ}
      (equation : ∀ l r : Expr (Δ ⋈ α), boundary = .eq l r → Eq_e (Ξ ⋈ bind) l r)
      (filler : ¬ boundary.isEq → Wf_e (Ξ ⋈ bind) (σ (C.inl (C.singleSlot α))))
      (declared : ¬ boundary.isEq →
          Eq_bd (Ξ ⋈ bind) ((Ξ ⋈ bind).boundaryOf (σ (C.inl (C.singleSlot α))))
            boundary)
      (hrest : Wf_s Ξ
          (dTel.instantiate (fun ⦃β⦄ (i : C.single α ∋ β) => σ (C.inl i)) rest)
          (fun ⦃β⦄ (j : Ω ∋ β) => σ (C.inr j))) :
      Wf_s Ξ (dTel.cons bind boundary rest) σ

/-- Two substitutions agree as fillings of a telescope when, at every slot whose
declaration is not an equation, their fillers are equal over the ambient
extended by the entries that slot binds; in that declaration and those entries
the slots before it are filled by the first substitution. -/
inductive Eq_s : {Δ Ω : C.Arity} → Ambient Δ → dTel Δ Ω → Subst Ω Δ → Subst Ω Δ → Prop
  where
  | nil {Δ : C.Arity} {Ξ : Ambient Δ} {σ θ : Subst 1 Δ} : Eq_s Ξ .nil σ θ
  | cons {Δ α Ω : C.Arity} {Ξ : Ambient Δ} {bind : dTel Δ α} {boundary : Bd (Δ ⋈ α)}
      {rest : dTel (Δ ⋈ C.single α) Ω} {σ θ : Subst (C.single α ⋈ Ω) Δ}
      (slot : ¬ boundary.isEq →
          Eq_e (Ξ ⋈ bind) (σ (C.inl (C.singleSlot α))) (θ (C.inl (C.singleSlot α))))
      (hrest : Eq_s Ξ
          (dTel.instantiate (fun ⦃β⦄ (i : C.single α ∋ β) => σ (C.inl i)) rest)
          (fun ⦃β⦄ (j : Ω ∋ β) => σ (C.inr j))
          (fun ⦃β⦄ (j : Ω ∋ β) => θ (C.inr j))) :
      Eq_s Ξ (dTel.cons bind boundary rest) σ θ

/-- A declaration `β` is well formed over an ambient `Ξ` with bound entries `Θ`:
`sort` always is, `of S` is when `S` is well formed over `Ξ ⋈ Θ` with computed
boundary equal to `sort`, and `eq l r` is when `l` and `r` are well formed over
`Ξ ⋈ Θ` with equal computed boundaries. -/
inductive Wf_bd : {Δ Λ : C.Arity} → Ambient Δ → dTel Δ Λ → Bd (Δ ⋈ Λ) → Prop where
  | sort {Δ Λ : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Λ} : Wf_bd Ξ Θ .sort
  | of {Δ Λ : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Λ} {S : Expr (Δ ⋈ Λ)}
      (hS : Wf_e (Ξ ⋈ Θ) S)
      (hsort : Eq_bd (Ξ ⋈ Θ) ((Ξ ⋈ Θ).boundaryOf S) .sort) :
      Wf_bd Ξ Θ (.of S)
  | eq {Δ Λ : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Λ} {l r : Expr (Δ ⋈ Λ)}
      (hl : Wf_e (Ξ ⋈ Θ) l) (hr : Wf_e (Ξ ⋈ Θ) r)
      (heq : Eq_bd (Ξ ⋈ Θ) ((Ξ ⋈ Θ).boundaryOf l) ((Ξ ⋈ Θ).boundaryOf r)) :
      Wf_bd Ξ Θ (.eq l r)

/-- A telescope over an ambient is well formed when every slot binds a
well-formed telescope and declares a well-formed boundary, both over the
ambient extended by the preceding slots. -/
inductive Wf_t : {Δ Ω : C.Arity} → Ambient Δ → dTel Δ Ω → Prop where
  | nil {Δ : C.Arity} {Ξ : Ambient Δ} : Wf_t Ξ .nil
  | cons {Δ α Ω : C.Arity} {Ξ : Ambient Δ} {bind : dTel Δ α} {boundary : Bd (Δ ⋈ α)}
      {rest : dTel (Δ ⋈ C.single α) Ω}
      (hbind : Wf_t Ξ bind) (hboundary : Wf_bd Ξ bind boundary)
      (hrest : Wf_t (Ξ ⋈ dTel.cons bind boundary .nil) rest) :
      Wf_t Ξ (dTel.cons bind boundary rest)

end

/-! ### Notation

`Ξ ⊢ e`, `Ξ ⊢ e ≈ e'`, `Ξ ⊢ β ≈ β'`, `Ξ ⊢ σ : Θ` and `Ξ ⊢ σ ≈ θ : Θ` for the
judgements over the ambient `Ξ`.  The operands parse at precedence 51, so
`Ξ ⊢ e ≈ e'` is the equality judgement. -/

@[inherit_doc Wf_e] notation:50 Ξ " ⊢ " e:51 => Wf_e Ξ e
@[inherit_doc Eq_e] notation:50 Ξ " ⊢ " e:51 " ≈ " e':51 => Eq_e Ξ e e'
@[inherit_doc Eq_bd] notation:50 Ξ " ⊢ " β:51 " ≈ " β':51 => Eq_bd Ξ β β'
@[inherit_doc Wf_s] notation:50 Ξ " ⊢ " σ:51 " : " Θ:51 => Wf_s Ξ Θ σ
@[inherit_doc Eq_s] notation:50 Ξ " ⊢ " σ:51 " ≈ " θ:51 " : " Θ:51 => Eq_s Ξ Θ σ θ

/-! ### Fillings, slot by slot

`σ` fills `Θ` exactly when at every slot `z`, over the ambient extended by
`σ ⋆ Θ.binding z`: if `σ ⋆ Θ.declaration z` is an equation its sides are equal,
and otherwise the filler `σ z` is well formed with boundary equal to
`σ ⋆ Θ.declaration z`.  Two fillings agree exactly when their fillers are equal
at every non-equational slot. -/

/-- If `σ` fills `Θ` and `σ ⋆ Θ.declaration z` is `.eq l r`, then `l` and `r` are
equal over `Ξ ⋈ σ ⋆ Θ.binding z`. -/
theorem Wf_s.equation {Δ : C.Arity} {Ξ : Ambient Δ} :
  ∀ {Ω : C.Arity} {Θ : dTel Δ Ω} {σ : Subst Ω Δ}, Wf_s Ξ Θ σ →
    ∀ ⦃Λ : C.Arity⦄ (z : Ω ∋ Λ) (l r : Expr (Δ ⋈ Λ)),
      σ ⋆ Θ.declaration z = .eq l r → Eq_e (Ξ ⋈ σ ⋆ Θ.binding z) l r
  | _, _, _, .nil, _, z => (C.unit_is_empty z).elim
  | _, _, _, .cons equation _ _ hrest, _, z => by
      induction z using slotCases with
      | head =>
        intro l r h
        rw [dTel.declaration_head_instantiate] at h
        convert equation l r h using 2
        apply dTel.binding_head_instantiate
      | tail y =>
        intro l r h
        rw [dTel.declaration_tail_instantiate] at h
        convert Wf_s.equation hrest y l r h using 2
        apply dTel.binding_tail_instantiate

/-- If `σ` fills `Θ` and `σ ⋆ Θ.declaration z` is not an equation, then `σ z` is
well formed over `Ξ ⋈ σ ⋆ Θ.binding z`. -/
theorem Wf_s.filler {Δ : C.Arity} {Ξ : Ambient Δ} :
  ∀ {Ω : C.Arity} {Θ : dTel Δ Ω} {σ : Subst Ω Δ}, Wf_s Ξ Θ σ →
    ∀ ⦃Λ : C.Arity⦄ (z : Ω ∋ Λ), ¬ (σ ⋆ Θ.declaration z).isEq →
      Wf_e (Ξ ⋈ σ ⋆ Θ.binding z) (σ z)
  | _, _, _, .nil, _, z => (C.unit_is_empty z).elim
  | _, _, _, .cons _ filler _ hrest, _, z => by
      induction z using slotCases with
      | head =>
        intro hne
        rw [dTel.declaration_head_instantiate] at hne
        convert filler hne using 2
        apply dTel.binding_head_instantiate
      | tail y =>
        intro hne
        rw [dTel.declaration_tail_instantiate] at hne
        convert Wf_s.filler hrest y hne using 2
        apply dTel.binding_tail_instantiate

/-- If `σ` fills `Θ` and `σ ⋆ Θ.declaration z` is not an equation, then the
computed boundary of `σ z` is equal to `σ ⋆ Θ.declaration z` over
`Ξ ⋈ σ ⋆ Θ.binding z`. -/
theorem Wf_s.declared {Δ : C.Arity} {Ξ : Ambient Δ} :
  ∀ {Ω : C.Arity} {Θ : dTel Δ Ω} {σ : Subst Ω Δ}, Wf_s Ξ Θ σ →
    ∀ ⦃Λ : C.Arity⦄ (z : Ω ∋ Λ), ¬ (σ ⋆ Θ.declaration z).isEq →
      Eq_bd (Ξ ⋈ σ ⋆ Θ.binding z) ((Ξ ⋈ σ ⋆ Θ.binding z).boundaryOf (σ z))
        (σ ⋆ Θ.declaration z)
  | _, _, _, .nil, _, z => (C.unit_is_empty z).elim
  | _, _, _, .cons _ _ declared hrest, _, z => by
      induction z using slotCases with
      | head =>
        intro hne
        rw [dTel.declaration_head_instantiate] at hne ⊢
        convert declared hne using 3 <;> apply dTel.binding_head_instantiate
      | tail y =>
        intro hne
        rw [dTel.declaration_tail_instantiate] at hne ⊢
        convert Wf_s.declared hrest y hne using 1
        · congr 1
          apply dTel.binding_tail_instantiate
        · congr 2
          apply dTel.binding_tail_instantiate

/-- `σ` fills `dTel.actBase κ Θ` when at every slot `z`, over `Ξ` extended by
the entries `z` binds filled by `σ`, the declaration of `z` filled by `σ` has
equal sides if it is an equation, and otherwise `σ z` is well formed with
computed boundary equal to that declaration. -/
theorem Wf_s.slotwise_actBase {Δ : C.Arity} {Ξ : Ambient Δ} :
  ∀ {Γ Ω : C.Arity} (Θ : dTel Γ Ω) (κ : Subst Γ Δ) {σ : Subst Ω Δ},
    (∀ ⦃Λ : C.Arity⦄ (z : Ω ∋ Λ) (l r : Expr (Δ ⋈ Λ)),
        σ ⋆ (dTel.actBase κ Θ).declaration z = .eq l r →
        Eq_e (Ξ ⋈ σ ⋆ (dTel.actBase κ Θ).binding z) l r) →
    (∀ ⦃Λ : C.Arity⦄ (z : Ω ∋ Λ),
        ¬ (σ ⋆ (dTel.actBase κ Θ).declaration z).isEq →
        Wf_e (Ξ ⋈ σ ⋆ (dTel.actBase κ Θ).binding z) (σ z)) →
    (∀ ⦃Λ : C.Arity⦄ (z : Ω ∋ Λ),
        ¬ (σ ⋆ (dTel.actBase κ Θ).declaration z).isEq →
        Eq_bd (Ξ ⋈ σ ⋆ (dTel.actBase κ Θ).binding z)
          ((Ξ ⋈ σ ⋆ (dTel.actBase κ Θ).binding z).boundaryOf (σ z))
          (σ ⋆ (dTel.actBase κ Θ).declaration z)) →
    Wf_s Ξ (dTel.actBase κ Θ) σ
  | _, _, .nil, _, _, _, _, _ => .nil
  | _, _, .cons (α := α) _ _ rest, κ, σ, equation, filler, declared => by
      have hcat : dTel.actBase (Δ := Δ) (Subst.comp (Γ := 1) (Subst.lift κ (C.single α))
            (Subst.copair (Subst.id Δ) (fun ⦃β⦄ (i : C.single α ∋ β) => σ (C.inl i)))) rest
          = (fun ⦃β⦄ (i : C.single α ∋ β) => σ (C.inl i)) ⋆
              dTel.actBase (Subst.lift κ (C.single α)) rest :=
        dTel.actBase_comp _ _ rest
      apply Wf_s.cons
      case equation =>
        intro l r h
        convert equation (C.inl (C.singleSlot α)) l r ?_ using 2
        · symm
          apply dTel.binding_head_instantiate
        · rw [← h]
          apply dTel.declaration_head_instantiate
      case filler =>
        intro hne
        convert filler (C.inl (C.singleSlot α)) ?_ using 2
        · symm
          apply dTel.binding_head_instantiate
        · convert hne using 2
          apply dTel.declaration_head_instantiate
      case declared =>
        intro hne
        convert declared (C.inl (C.singleSlot α)) ?_ using 3
        · symm
          apply dTel.binding_head_instantiate
        · symm
          apply dTel.binding_head_instantiate
        · symm
          apply dTel.declaration_head_instantiate
        · convert hne using 2
          apply dTel.declaration_head_instantiate
      case hrest =>
        rw [← hcat]
        apply Wf_s.slotwise_actBase
        · intro γ y l r h
          rw [hcat] at h ⊢
          convert equation (C.inr y) l r ?_ using 2
          · symm
            apply dTel.binding_tail_instantiate
          · rw [← h]
            apply dTel.declaration_tail_instantiate
        · intro γ y hne
          rw [hcat] at hne ⊢
          convert filler (C.inr y) ?_ using 2
          · symm
            apply dTel.binding_tail_instantiate
          · convert hne using 2
            apply dTel.declaration_tail_instantiate
        · intro γ y hne
          rw [hcat] at hne ⊢
          convert declared (C.inr y) ?_ using 1
          · congr 1
            symm
            apply dTel.binding_tail_instantiate
          · congr 2
            symm
            apply dTel.binding_tail_instantiate
          · symm
            apply dTel.declaration_tail_instantiate
          · convert hne using 2
            apply dTel.declaration_tail_instantiate

/-- `σ` fills `Θ` when at every slot `z`, over `Ξ ⋈ σ ⋆ Θ.binding z`,
`σ ⋆ Θ.declaration z` has equal sides if it is an equation, and otherwise `σ z`
is well formed with computed boundary equal to `σ ⋆ Θ.declaration z`. -/
theorem Wf_s.slotwise
    {Δ Ω : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Ω} {σ : Subst Ω Δ}
    (equation : ∀ ⦃Λ : C.Arity⦄ (z : Ω ∋ Λ) (l r : Expr (Δ ⋈ Λ)),
        σ ⋆ Θ.declaration z = .eq l r → Eq_e (Ξ ⋈ σ ⋆ Θ.binding z) l r)
    (filler : ∀ ⦃Λ : C.Arity⦄ (z : Ω ∋ Λ), ¬ (σ ⋆ Θ.declaration z).isEq →
        Wf_e (Ξ ⋈ σ ⋆ Θ.binding z) (σ z))
    (declared : ∀ ⦃Λ : C.Arity⦄ (z : Ω ∋ Λ), ¬ (σ ⋆ Θ.declaration z).isEq →
        Eq_bd (Ξ ⋈ σ ⋆ Θ.binding z) ((Ξ ⋈ σ ⋆ Θ.binding z).boundaryOf (σ z))
          (σ ⋆ Θ.declaration z)) :
  Wf_s Ξ Θ σ
  := by
  rw [← dTel.actBase_id Θ]
  apply Wf_s.slotwise_actBase
  · rw [dTel.actBase_id]
    apply equation
  · rw [dTel.actBase_id]
    apply filler
  · rw [dTel.actBase_id]
    apply declared

/-- If `σ` and `θ` agree as fillings of `Θ` and `σ ⋆ Θ.declaration z` is not an
equation, then `σ z` and `θ z` are equal over `Ξ ⋈ σ ⋆ Θ.binding z`. -/
theorem Eq_s.slot {Δ : C.Arity} {Ξ : Ambient Δ} :
  ∀ {Ω : C.Arity} {Θ : dTel Δ Ω} {σ θ : Subst Ω Δ}, Eq_s Ξ Θ σ θ →
    ∀ ⦃Λ : C.Arity⦄ (z : Ω ∋ Λ), ¬ (σ ⋆ Θ.declaration z).isEq →
      Eq_e (Ξ ⋈ σ ⋆ Θ.binding z) (σ z) (θ z)
  | _, _, _, _, .nil, _, z => (C.unit_is_empty z).elim
  | _, _, _, _, .cons slot hrest, _, z => by
      induction z using slotCases with
      | head =>
        intro hne
        rw [dTel.declaration_head_instantiate] at hne
        convert slot hne using 2
        apply dTel.binding_head_instantiate
      | tail y =>
        intro hne
        rw [dTel.declaration_tail_instantiate] at hne
        convert Eq_s.slot hrest y hne using 2
        apply dTel.binding_tail_instantiate

/-- `σ` and `θ` agree as fillings of `dTel.actBase κ Θ` when at every slot `z`
whose declaration filled by `σ` is not an equation, `σ z` and `θ z` are equal
over `Ξ` extended by the entries `z` binds filled by `σ`. -/
theorem Eq_s.slotwise_actBase {Δ : C.Arity} {Ξ : Ambient Δ} :
  ∀ {Γ Ω : C.Arity} (Θ : dTel Γ Ω) (κ : Subst Γ Δ) {σ θ : Subst Ω Δ},
    (∀ ⦃Λ : C.Arity⦄ (z : Ω ∋ Λ),
        ¬ (σ ⋆ (dTel.actBase κ Θ).declaration z).isEq →
        Eq_e (Ξ ⋈ σ ⋆ (dTel.actBase κ Θ).binding z) (σ z) (θ z)) →
    Eq_s Ξ (dTel.actBase κ Θ) σ θ
  | _, _, .nil, _, _, _, _ => .nil
  | _, _, .cons (α := α) _ _ rest, κ, σ, θ, slot => by
      have hcat : dTel.actBase (Δ := Δ) (Subst.comp (Γ := 1) (Subst.lift κ (C.single α))
            (Subst.copair (Subst.id Δ) (fun ⦃β⦄ (i : C.single α ∋ β) => σ (C.inl i)))) rest
          = (fun ⦃β⦄ (i : C.single α ∋ β) => σ (C.inl i)) ⋆
              dTel.actBase (Subst.lift κ (C.single α)) rest :=
        dTel.actBase_comp _ _ rest
      apply Eq_s.cons
      case slot =>
        intro hne
        convert slot (C.inl (C.singleSlot α)) ?_ using 2
        · symm
          apply dTel.binding_head_instantiate
        · convert hne using 2
          apply dTel.declaration_head_instantiate
      case hrest =>
        rw [← hcat]
        apply Eq_s.slotwise_actBase
        intro γ y hne
        rw [hcat] at hne ⊢
        convert slot (C.inr y) ?_ using 2
        · symm
          apply dTel.binding_tail_instantiate
        · convert hne using 2
          apply dTel.declaration_tail_instantiate

/-- `σ` and `θ` agree as fillings of `Θ` when at every slot `z` for which
`σ ⋆ Θ.declaration z` is not an equation, `σ z` and `θ z` are equal over
`Ξ ⋈ σ ⋆ Θ.binding z`. -/
theorem Eq_s.slotwise
    {Δ Ω : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Ω} {σ θ : Subst Ω Δ}
    (slot : ∀ ⦃Λ : C.Arity⦄ (z : Ω ∋ Λ), ¬ (σ ⋆ Θ.declaration z).isEq →
        Eq_e (Ξ ⋈ σ ⋆ Θ.binding z) (σ z) (θ z)) :
  Eq_s Ξ Θ σ θ
  := by
  rw [← dTel.actBase_id Θ]
  apply Eq_s.slotwise_actBase
  rw [dTel.actBase_id]
  apply slot

/-- A well-formed filling agrees with itself. -/
theorem Eq_s.refl
    {Δ Ω : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Ω} {σ : Subst Ω Δ}
    (h : Wf_s Ξ Θ σ) :
  Eq_s Ξ Θ σ σ
  := Eq_s.slotwise (fun ⦃_⦄ z hne => .refl (h.filler z hne))

/-- A well-formed filling agrees with itself. -/
theorem Wf_s.refl
    {Δ Ω : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Ω} {σ : Subst Ω Δ}
    (h : Wf_s Ξ Θ σ) :
  Eq_s Ξ Θ σ σ
  := Eq_s.refl h

/-! ### Fillings of concatenations -/

/-- If `κ` fills `dTel.concatenate Θ X`, its restriction to `Ω` fills `Θ`. -/
theorem Wf_s.concatenate_left
    {Δ Ω Φ : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Ω} {X : dTel (Δ ⋈ Ω) Φ}
    {κ : Subst (Ω ⋈ Φ) Δ}
    (h : Wf_s Ξ (dTel.concatenate Θ X) κ) :
  Wf_s Ξ Θ (fun ⦃α⦄ (w : Ω ∋ α) => κ (C.inl w))
  := by
  apply Wf_s.slotwise
  case equation =>
    intro Λ w l r hlr
    rw [← dTel.declaration_left_instantiate Θ X] at hlr
    convert h.equation (C.inl w) l r hlr using 2
    symm
    apply dTel.binding_left_instantiate
  case filler =>
    intro Λ w hne
    rw [← dTel.declaration_left_instantiate Θ X] at hne
    convert h.filler (C.inl w) hne using 2
    symm
    apply dTel.binding_left_instantiate
  case declared =>
    intro Λ w hne
    rw [← dTel.declaration_left_instantiate Θ X] at hne ⊢
    convert h.declared (C.inl w) hne using 1
    · congr 1
      symm
      apply dTel.binding_left_instantiate
    · congr 2
      symm
      apply dTel.binding_left_instantiate

/-- If `κ` fills `dTel.concatenate Θ X`, its restriction to `Φ` fills `X`
instantiated by its restriction to `Ω`. -/
theorem Wf_s.concatenate_right
    {Δ Ω Φ : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Ω} {X : dTel (Δ ⋈ Ω) Φ}
    {κ : Subst (Ω ⋈ Φ) Δ}
    (h : Wf_s Ξ (dTel.concatenate Θ X) κ) :
  Wf_s Ξ (dTel.instantiate (fun ⦃α⦄ (w : Ω ∋ α) => κ (C.inl w)) X)
    (fun ⦃α⦄ (z : Φ ∋ α) => κ (C.inr z))
  := by
  apply Wf_s.slotwise
  case equation =>
    intro Λ z l r hlr
    rw [dTel.declaration_right_instantiate Θ] at hlr
    convert h.equation (C.inr z) l r hlr using 2
    apply dTel.binding_right_instantiate
  case filler =>
    intro Λ z hne
    rw [dTel.declaration_right_instantiate Θ] at hne
    convert h.filler (C.inr z) hne using 2
    apply dTel.binding_right_instantiate
  case declared =>
    intro Λ z hne
    rw [dTel.declaration_right_instantiate Θ] at hne ⊢
    convert h.declared (C.inr z) hne using 1
    · congr 1
      apply dTel.binding_right_instantiate
    · congr 2
      apply dTel.binding_right_instantiate

/-- If `κ` and `κ'` agree as fillings of `dTel.concatenate Θ X`, their
restrictions to `Ω` agree as fillings of `Θ`. -/
theorem Eq_s.concatenate_left
    {Δ Ω Φ : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Ω} {X : dTel (Δ ⋈ Ω) Φ}
    {κ κ' : Subst (Ω ⋈ Φ) Δ}
    (h : Eq_s Ξ (dTel.concatenate Θ X) κ κ') :
  Eq_s Ξ Θ (fun ⦃α⦄ (w : Ω ∋ α) => κ (C.inl w))
    (fun ⦃α⦄ (w : Ω ∋ α) => κ' (C.inl w))
  := by
  apply Eq_s.slotwise
  intro Λ w hne
  rw [← dTel.declaration_left_instantiate Θ X] at hne
  convert h.slot (C.inl w) hne using 2
  symm
  apply dTel.binding_left_instantiate

/-- If `κ` and `κ'` agree as fillings of `dTel.concatenate Θ X`, their
restrictions to `Φ` agree as fillings of `X` instantiated by the restriction of
`κ` to `Ω`. -/
theorem Eq_s.concatenate_right
    {Δ Ω Φ : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Ω} {X : dTel (Δ ⋈ Ω) Φ}
    {κ κ' : Subst (Ω ⋈ Φ) Δ}
    (h : Eq_s Ξ (dTel.concatenate Θ X) κ κ') :
  Eq_s Ξ (dTel.instantiate (fun ⦃α⦄ (w : Ω ∋ α) => κ (C.inl w)) X)
    (fun ⦃α⦄ (z : Φ ∋ α) => κ (C.inr z))
    (fun ⦃α⦄ (z : Φ ∋ α) => κ' (C.inr z))
  := by
  apply Eq_s.slotwise
  intro Λ z hne
  rw [dTel.declaration_right_instantiate Θ] at hne
  convert h.slot (C.inr z) hne using 2
  apply dTel.binding_right_instantiate

section

variable {Δ Ω Φ : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Ω} {X : dTel (Δ ⋈ Ω) Φ}
  {σ σ' : Subst Ω Δ} {τ τ' : Subst Φ Δ}

/-- If `σ` fills `Θ` and `τ` fills `X` instantiated by `σ`, then
`Subst.copair σ τ` fills `dTel.concatenate Θ X`. -/
theorem Wf_s.concatenate
    (hσ : Wf_s Ξ Θ σ) (hτ : Wf_s Ξ (dTel.instantiate σ X) τ) :
  Wf_s Ξ (dTel.concatenate Θ X) (Subst.copair σ τ)
  := by
  apply Wf_s.slotwise
  case equation =>
    intro Λ x l r hlr
    rcases C.cover Ω Φ x with ⟨w, rfl⟩ | ⟨z, rfl⟩
    · rw [dTel.declaration_left_copair] at hlr
      convert hσ.equation w l r hlr using 2
      apply dTel.binding_left_copair
    · rw [dTel.declaration_right_copair] at hlr
      convert hτ.equation z l r hlr using 2
      apply dTel.binding_right_copair
  case filler =>
    intro Λ x hne
    rcases C.cover Ω Φ x with ⟨w, rfl⟩ | ⟨z, rfl⟩
    · rw [dTel.declaration_left_copair] at hne
      rw [Subst.copair_inl]
      convert hσ.filler w hne using 2
      apply dTel.binding_left_copair
    · rw [dTel.declaration_right_copair] at hne
      rw [Subst.copair_inr]
      convert hτ.filler z hne using 2
      apply dTel.binding_right_copair
  case declared =>
    intro Λ x hne
    rcases C.cover Ω Φ x with ⟨w, rfl⟩ | ⟨z, rfl⟩
    · rw [dTel.declaration_left_copair] at hne ⊢
      rw [Subst.copair_inl]
      convert hσ.declared w hne using 1
      · congr 1
        apply dTel.binding_left_copair
      · congr 2
        apply dTel.binding_left_copair
    · rw [dTel.declaration_right_copair] at hne ⊢
      rw [Subst.copair_inr]
      convert hτ.declared z hne using 1
      · congr 1
        apply dTel.binding_right_copair
      · congr 2
        apply dTel.binding_right_copair

/-- If `σ` and `σ'` agree as fillings of `Θ`, and `τ` and `τ'` agree as fillings
of `X` instantiated by `σ`, then `Subst.copair σ τ` and `Subst.copair σ' τ'`
agree as fillings of `dTel.concatenate Θ X`. -/
theorem Eq_s.concatenate
    (hσ : Eq_s Ξ Θ σ σ') (hτ : Eq_s Ξ (dTel.instantiate σ X) τ τ') :
  Eq_s Ξ (dTel.concatenate Θ X) (Subst.copair σ τ) (Subst.copair σ' τ')
  := by
  apply Eq_s.slotwise
  intro Λ x hne
  rcases C.cover Ω Φ x with ⟨w, rfl⟩ | ⟨z, rfl⟩
  · rw [dTel.declaration_left_copair] at hne
    rw [Subst.copair_inl, Subst.copair_inl]
    convert hσ.slot w hne using 2
    apply dTel.binding_left_copair
  · rw [dTel.declaration_right_copair] at hne
    rw [Subst.copair_inr, Subst.copair_inr]
    convert hτ.slot z hne using 2
    apply dTel.binding_right_copair

end

/-- If `σ` fills `dTel.cons bind boundary rest`, its first filler fills
`dTel.cons bind boundary .nil`. -/
theorem Wf_s.head
    {Δ α Ω : C.Arity} {Ξ : Ambient Δ} {bind : dTel Δ α} {boundary : Bd (Δ ⋈ α)}
    {rest : dTel (Δ ⋈ C.single α) Ω} {σ : Subst (C.single α ⋈ Ω) Δ}
    (h : Wf_s Ξ (dTel.cons bind boundary rest) σ) :
  Wf_s Ξ (dTel.cons bind boundary (.nil : dTel (Δ ⋈ C.single α) 1))
    (fun ⦃β⦄ (i : C.single α ∋ β) => σ (C.inl i))
  := Wf_s.concatenate_left (Θ := dTel.cons bind boundary .nil) h

/-- If `σ` fills `dTel.cons bind boundary rest`, its remaining fillers fill
`rest` instantiated by its first filler. -/
theorem Wf_s.tail
    {Δ α Ω : C.Arity} {Ξ : Ambient Δ} {bind : dTel Δ α} {boundary : Bd (Δ ⋈ α)}
    {rest : dTel (Δ ⋈ C.single α) Ω} {σ : Subst (C.single α ⋈ Ω) Δ}
    (h : Wf_s Ξ (dTel.cons bind boundary rest) σ) :
  Wf_s Ξ (dTel.instantiate (fun ⦃β⦄ (i : C.single α ∋ β) => σ (C.inl i)) rest)
    (fun ⦃β⦄ (j : Ω ∋ β) => σ (C.inr j))
  := Wf_s.concatenate_right (Θ := dTel.cons bind boundary .nil) h

/-- If `σ` and `θ` agree as fillings of `dTel.cons bind boundary rest`, their
remaining fillers agree as fillings of `rest` instantiated by the first filler
of `σ`. -/
theorem Eq_s.tail
    {Δ α Ω : C.Arity} {Ξ : Ambient Δ} {bind : dTel Δ α} {boundary : Bd (Δ ⋈ α)}
    {rest : dTel (Δ ⋈ C.single α) Ω} {σ θ : Subst (C.single α ⋈ Ω) Δ}
    (h : Eq_s Ξ (dTel.cons bind boundary rest) σ θ) :
  Eq_s Ξ (dTel.instantiate (fun ⦃β⦄ (i : C.single α ∋ β) => σ (C.inl i)) rest)
    (fun ⦃β⦄ (j : Ω ∋ β) => σ (C.inr j))
    (fun ⦃β⦄ (j : Ω ∋ β) => θ (C.inr j))
  := Eq_s.concatenate_right (Θ := dTel.cons bind boundary .nil) h

/-- `Subst.single t` fills `dTel.cons Θ β .nil` exactly when, over `Ξ ⋈ Θ`, `β`
has equal sides if it is an equation, and otherwise `t` is well formed with
computed boundary equal to `β`. -/
theorem Wf_s.single_iff
    {Δ α : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ α} {β : Bd (Δ ⋈ α)}
    (t : Expr (Δ ⋈ α)) :
  Wf_s Ξ (dTel.cons Θ β .nil) (Subst.single t)
    ↔ (∀ l r : Expr (Δ ⋈ α), β = .eq l r → Eq_e (Ξ ⋈ Θ) l r) ∧
        (¬ β.isEq → Wf_e (Ξ ⋈ Θ) t) ∧
        (¬ β.isEq → Eq_bd (Ξ ⋈ Θ) ((Ξ ⋈ Θ).boundaryOf t) β)
  := by
  constructor
  · intro h
    constructor
    · intro l r he
      convert h.equation (C.inl (C.singleSlot α)) l r ?_ using 2
      · symm
        apply dTel.binding_head_instantiate
      · rw [← he]
        apply dTel.declaration_head_instantiate
    constructor
    · intro hne
      convert h.filler (C.inl (C.singleSlot α)) ?_ using 2
      · symm
        apply dTel.binding_head_instantiate
      · convert hne using 2
        apply dTel.declaration_head_instantiate
    · intro hne
      convert h.declared (C.inl (C.singleSlot α)) ?_ using 3
      · symm
        apply dTel.binding_head_instantiate
      · symm
        apply dTel.binding_head_instantiate
      · symm
        apply dTel.declaration_head_instantiate
      · convert hne using 2
        apply dTel.declaration_head_instantiate
  · rintro ⟨heq, hfill, hdecl⟩
    apply Wf_s.cons heq hfill hdecl
    apply Wf_s.nil

/-- `Subst.single t` and `Subst.single t'` agree as fillings of
`dTel.cons Θ β .nil` exactly when `t` and `t'` are equal over `Ξ ⋈ Θ` whenever
`β` is not an equation. -/
theorem Eq_s.single_iff
    {Δ α : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ α} {β : Bd (Δ ⋈ α)}
    (t t' : Expr (Δ ⋈ α)) :
  Eq_s Ξ (dTel.cons Θ β .nil) (Subst.single t) (Subst.single t')
    ↔ (¬ β.isEq → Eq_e (Ξ ⋈ Θ) t t')
  := by
  constructor
  · intro h hne
    convert h.slot (C.inl (C.singleSlot α)) ?_ using 2
    · symm
      apply dTel.binding_head_instantiate
    · convert hne using 2
      apply dTel.declaration_head_instantiate
  · intro h
    apply Eq_s.cons h
    apply Eq_s.nil

/-! ### Equality of boundaries -/

/-- Equality of boundaries is symmetric. -/
theorem Eq_bd.symm {Δ : C.Arity} {Ξ : Ambient Δ} :
  ∀ {β β' : Bd Δ}, Eq_bd Ξ β β' → Eq_bd Ξ β' β
  | _, _, .sort => .sort
  | _, _, .of h => .of h.symm
  | _, _, .eq hl hr => .eq hl.symm hr.symm

/-- Equality of boundaries is transitive. -/
theorem Eq_bd.trans {Δ : C.Arity} {Ξ : Ambient Δ} :
  ∀ {β β' β'' : Bd Δ}, Eq_bd Ξ β β' → Eq_bd Ξ β' β'' → Eq_bd Ξ β β''
  | _, _, _, .sort, .sort => .sort
  | _, _, _, .of h, .of h' => .of (h.trans h')
  | _, _, _, .eq hl hr, .eq hl' hr' => .eq (hl.trans hl') (hr.trans hr')

/-- A boundary equal to `.eq l r` is `.eq l' r'` with `l` equal to `l'` and `r`
equal to `r'`. -/
theorem Eq_bd.eq_inv {Δ : C.Arity} {Ξ : Ambient Δ} {l r : Expr Δ} {β : Bd Δ} :
  Eq_bd Ξ (.eq l r) β → ∃ l' r', β = .eq l' r' ∧ Eq_e Ξ l l' ∧ Eq_e Ξ r r'
  | .eq hl hr => ⟨_, _, rfl, hl, hr⟩

/-- Substituting agreeing fillings `σ` and `θ` of a well-formed telescope `Θ`
into boundaries equal over `Ξ ⋈ Θ` gives boundaries equal over `Ξ`. -/
theorem Eq_bd.congr
    {Δ Ω : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Ω}
    (σ θ : Subst Ω Δ) (hΘ : Wf_t Ξ Θ) (hσ : Wf_s Ξ Θ σ) (hθ : Wf_s Ξ Θ θ)
    (agree : Eq_s Ξ Θ σ θ) :
  ∀ {β β' : Bd (Δ ⋈ Ω)}, Eq_bd (Ξ ⋈ Θ) β β' → Eq_bd Ξ (σ ⋆ β) (θ ⋆ β')
  | _, _, .sort => .sort
  | _, _, .of h => .of (Eq_e.congr σ θ hΘ hσ hθ agree h)
  | _, _, .eq hl hr =>
      .eq (Eq_e.congr σ θ hΘ hσ hθ agree hl) (Eq_e.congr σ θ hΘ hσ hθ agree hr)

/-! ### Telescopes -/

private def Wf_t.parts : {Δ Ω : C.Arity} → Ambient Δ → dTel Δ Ω → Prop
  | _, _, _, .nil => True
  | _, _, Ξ, .cons bind boundary rest =>
      Wf_t Ξ bind ∧ Wf_bd Ξ bind boundary ∧
        Wf_t (Ξ ⋈ dTel.cons bind boundary .nil) rest

private theorem Wf_t.toParts {Δ : C.Arity} {Ξ : Ambient Δ} :
  ∀ {Ω : C.Arity} {Θ : dTel Δ Ω}, Wf_t Ξ Θ → Wf_t.parts Ξ Θ
  | _, _, .nil => trivial
  | _, _, .cons hbind hboundary hrest => ⟨hbind, hboundary, hrest⟩

/-- If `dTel.cons bind boundary rest` is well formed over `Ξ`, then `bind` is well
formed over `Ξ`, `boundary` is well formed over `Ξ` with bound entries `bind`,
and `rest` is well formed over `Ξ` extended by the first slot. -/
theorem Wf_t.cons_inv
    {Δ α Ω : C.Arity} {Ξ : Ambient Δ} {bind : dTel Δ α} {boundary : Bd (Δ ⋈ α)}
    {rest : dTel (Δ ⋈ C.single α) Ω}
    (h : Wf_t Ξ (dTel.cons bind boundary rest)) :
  Wf_t Ξ bind ∧ Wf_bd Ξ bind boundary ∧
    Wf_t (Ξ ⋈ dTel.cons bind boundary .nil) rest
  := Wf_t.toParts h

/-- If `Θ` is well formed over `Ξ` and `X` over `Ξ ⋈ Θ`, then
`dTel.concatenate Θ X` is well formed over `Ξ`. -/
theorem Wf_t.concatenate {Δ : C.Arity} {Ξ : Ambient Δ} :
  ∀ {Ω Φ : C.Arity} {Θ : dTel Δ Ω} {X : dTel (Δ ⋈ Ω) Φ},
    Wf_t Ξ Θ → Wf_t (Ξ ⋈ Θ) X → Wf_t Ξ (dTel.concatenate Θ X)
  | _, _, _, _, .nil, hX => by
      convert hX using 1
      symm
      apply dTel.concatenate_nil
  | _, _, _, _, .cons hbind hboundary hrest, hX => by
      apply Wf_t.cons hbind hboundary
      apply Wf_t.concatenate hrest
      rw [dTel.concatenate_assoc]
      apply hX

/-- A declaration well formed over `Ξ ⋈ Θ` with bound entries `Ψ` is well formed
over `Ξ` with bound entries `Θ ⋈ Ψ`. -/
theorem Wf_bd.concatenate
    {Δ Λ Φ : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Λ} {Ψ : dTel (Δ ⋈ Λ) Φ}
    {β : Bd ((Δ ⋈ Λ) ⋈ Φ)}
    (h : Wf_bd (Ξ ⋈ Θ) Ψ β) :
  Wf_bd Ξ (dTel.concatenate Θ Ψ) β
  := by
  cases h with
  | sort => apply Wf_bd.sort
  | of hS hsort =>
      rw [dTel.concatenate_assoc] at hS hsort
      apply Wf_bd.of hS hsort
  | eq hl hr heq =>
      rw [dTel.concatenate_assoc] at hl hr heq
      apply Wf_bd.eq hl hr heq

/-- The left side of a well-formed equational declaration is well formed. -/
theorem Wf_bd.eq_left
    {Δ Λ : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Λ} {l r : Expr (Δ ⋈ Λ)} :
  Wf_bd Ξ Θ (.eq l r) → Wf_e (Ξ ⋈ Θ) l
  | .eq hl _ _ => hl

/-- The right side of a well-formed equational declaration is well formed. -/
theorem Wf_bd.eq_right
    {Δ Λ : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Λ} {l r : Expr (Δ ⋈ Λ)} :
  Wf_bd Ξ Θ (.eq l r) → Wf_e (Ξ ⋈ Θ) r
  | .eq _ hr _ => hr

/-- The two sides of a well-formed equational declaration have equal computed
boundaries. -/
theorem Wf_bd.eq_boundary
    {Δ Λ : C.Arity} {Ξ : Ambient Δ} {Θ : dTel Δ Λ} {l r : Expr (Δ ⋈ Λ)} :
  Wf_bd Ξ Θ (.eq l r) → Eq_bd (Ξ ⋈ Θ) ((Ξ ⋈ Θ).boundaryOf l) ((Ξ ⋈ Θ).boundaryOf r)
  | .eq _ _ heq => heq

/-- Two telescopes are equal over `Ξ` when both are empty, or both have a first
slot, the entries bound there are equal over `Ξ`, the declarations there are
equal over `Ξ` extended by the entries of the first telescope, and the remaining
slots are equal over `Ξ` extended by the first slot of the first telescope. -/
def Eq_t : {Δ Ω : C.Arity} → Ambient Δ → dTel Δ Ω → dTel Δ Ω → Prop
  | _, _, _, .nil, Θ' => Θ' = .nil
  | Δ, _, Ξ, .cons (α := α) (Δ := Ω) bind boundary rest, Θ' =>
      ∃ (bind' : dTel Δ α) (boundary' : Bd (Δ ⋈ α))
        (rest' : dTel (Δ ⋈ C.single α) Ω),
        Θ' = dTel.cons bind' boundary' rest' ∧ Eq_t Ξ bind bind' ∧
          Eq_bd (Ξ ⋈ bind) boundary boundary' ∧
          Eq_t (Ξ ⋈ dTel.cons bind boundary .nil) rest rest'

/-- The empty telescopes are equal. -/
theorem Eq_t.nil {Δ : C.Arity} {Ξ : Ambient Δ} :
  Eq_t Ξ (.nil : dTel Δ 1) .nil
  := rfl

/-- `dTel.cons bind boundary rest` and `dTel.cons bind' boundary' rest'` are equal
over `Ξ` when `bind` and `bind'` are, `boundary` and `boundary'` are equal over
`Ξ ⋈ bind`, and `rest` and `rest'` are equal over `Ξ` extended by the first slot
of the first telescope. -/
theorem Eq_t.cons
    {Δ α Ω : C.Arity} {Ξ : Ambient Δ} {bind bind' : dTel Δ α}
    {boundary boundary' : Bd (Δ ⋈ α)} {rest rest' : dTel (Δ ⋈ C.single α) Ω}
    (hbind : Eq_t Ξ bind bind')
    (hboundary : Eq_bd (Ξ ⋈ bind) boundary boundary')
    (hrest : Eq_t (Ξ ⋈ dTel.cons bind boundary .nil) rest rest') :
  Eq_t Ξ (dTel.cons bind boundary rest) (dTel.cons bind' boundary' rest')
  := ⟨bind', boundary', rest', rfl, hbind, hboundary, hrest⟩

/-- A telescope equal to the empty telescope is empty. -/
theorem Eq_t.nil_inv
    {Δ : C.Arity} {Ξ : Ambient Δ} {Θ' : dTel Δ 1}
    (h : Eq_t Ξ .nil Θ') :
  Θ' = .nil
  := h

/-- A telescope equal over `Ξ` to `dTel.cons bind boundary rest` is
`dTel.cons bind' boundary' rest'` with `bind'`, `boundary'` and `rest'`
satisfying the premises of `Eq_t.cons`. -/
theorem Eq_t.cons_inv
    {Δ α Ω : C.Arity} {Ξ : Ambient Δ} {bind : dTel Δ α} {boundary : Bd (Δ ⋈ α)}
    {rest : dTel (Δ ⋈ C.single α) Ω} {Θ' : dTel Δ (C.single α ⋈ Ω)}
    (h : Eq_t Ξ (dTel.cons bind boundary rest) Θ') :
  ∃ (bind' : dTel Δ α) (boundary' : Bd (Δ ⋈ α)) (rest' : dTel (Δ ⋈ C.single α) Ω),
    Θ' = dTel.cons bind' boundary' rest' ∧ Eq_t Ξ bind bind' ∧
      Eq_bd (Ξ ⋈ bind) boundary boundary' ∧
      Eq_t (Ξ ⋈ dTel.cons bind boundary .nil) rest rest'
  := h

/-- Two telescopes are equal over the ambients `Ξ` and `Ξ'` when both are empty,
or both have a first slot, the entries bound there are equal over `Ξ` and `Ξ'`,
the declarations there are equal over `Ξ` extended by the entries of the first
telescope and over `Ξ'` extended by those of the second, and the remaining slots
are equal over `Ξ` and `Ξ'` extended by the first slots of the first and of the
second telescope respectively. -/
def Eq_t.Both : {Δ Ω : C.Arity} →
    Ambient Δ → Ambient Δ → dTel Δ Ω → dTel Δ Ω → Prop
  | _, _, _, _, .nil, Θ' => Θ' = .nil
  | Δ, _, Ξ, Ξ', .cons (α := α) (Δ := Ω) bind boundary rest, Θ' =>
      ∃ (bind' : dTel Δ α) (boundary' : Bd (Δ ⋈ α))
        (rest' : dTel (Δ ⋈ C.single α) Ω),
        Θ' = dTel.cons bind' boundary' rest' ∧ Eq_t.Both Ξ Ξ' bind bind' ∧
          Eq_bd (Ξ ⋈ bind) boundary boundary' ∧
          Eq_bd (Ξ' ⋈ bind') boundary boundary' ∧
          Eq_t.Both (Ξ ⋈ dTel.cons bind boundary .nil)
            (Ξ' ⋈ dTel.cons bind' boundary' .nil) rest rest'

/-- The empty telescopes are equal over any two ambients. -/
theorem Eq_t.Both.nil {Δ : C.Arity} {Ξ Ξ' : Ambient Δ} :
  Eq_t.Both Ξ Ξ' (.nil : dTel Δ 1) .nil
  := rfl

/-- `dTel.cons bind boundary rest` and `dTel.cons bind' boundary' rest'` are equal
over `Ξ` and `Ξ'` when `bind` and `bind'` are, `boundary` and `boundary'` are
equal over `Ξ ⋈ bind` and over `Ξ' ⋈ bind'`, and `rest` and `rest'` are equal
over `Ξ` and `Ξ'` extended by the respective first slots. -/
theorem Eq_t.Both.cons
    {Δ α Ω : C.Arity} {Ξ Ξ' : Ambient Δ} {bind bind' : dTel Δ α}
    {boundary boundary' : Bd (Δ ⋈ α)} {rest rest' : dTel (Δ ⋈ C.single α) Ω}
    (hbind : Eq_t.Both Ξ Ξ' bind bind')
    (hboundary : Eq_bd (Ξ ⋈ bind) boundary boundary')
    (hboundary' : Eq_bd (Ξ' ⋈ bind') boundary boundary')
    (hrest : Eq_t.Both (Ξ ⋈ dTel.cons bind boundary .nil)
      (Ξ' ⋈ dTel.cons bind' boundary' .nil) rest rest') :
  Eq_t.Both Ξ Ξ' (dTel.cons bind boundary rest) (dTel.cons bind' boundary' rest')
  := ⟨bind', boundary', rest', rfl, hbind, hboundary, hboundary', hrest⟩

/-- A telescope equal over two ambients to the empty telescope is empty. -/
theorem Eq_t.Both.nil_inv
    {Δ : C.Arity} {Ξ Ξ' : Ambient Δ} {Θ' : dTel Δ 1}
    (h : Eq_t.Both Ξ Ξ' .nil Θ') :
  Θ' = .nil
  := h

/-- A telescope equal over `Ξ` and `Ξ'` to `dTel.cons bind boundary rest` is
`dTel.cons bind' boundary' rest'` with `bind'`, `boundary'` and `rest'`
satisfying the premises of `Eq_t.Both.cons`. -/
theorem Eq_t.Both.cons_inv
    {Δ α Ω : C.Arity} {Ξ Ξ' : Ambient Δ} {bind : dTel Δ α} {boundary : Bd (Δ ⋈ α)}
    {rest : dTel (Δ ⋈ C.single α) Ω} {Θ' : dTel Δ (C.single α ⋈ Ω)}
    (h : Eq_t.Both Ξ Ξ' (dTel.cons bind boundary rest) Θ') :
  ∃ (bind' : dTel Δ α) (boundary' : Bd (Δ ⋈ α)) (rest' : dTel (Δ ⋈ C.single α) Ω),
    Θ' = dTel.cons bind' boundary' rest' ∧ Eq_t.Both Ξ Ξ' bind bind' ∧
      Eq_bd (Ξ ⋈ bind) boundary boundary' ∧
      Eq_bd (Ξ' ⋈ bind') boundary boundary' ∧
      Eq_t.Both (Ξ ⋈ dTel.cons bind boundary .nil)
        (Ξ' ⋈ dTel.cons bind' boundary' .nil) rest rest'
  := h

/-- Telescopes equal over two ambients are equal over the first. -/
theorem Eq_t.Both.toEq_t {Δ : C.Arity} {Ξ Ξ' : Ambient Δ} :
  ∀ {Ω : C.Arity} {Θ Θ' : dTel Δ Ω}, Eq_t.Both Ξ Ξ' Θ Θ' → Eq_t Ξ Θ Θ'
  | _, .nil, _, h => by
      obtain rfl := Eq_t.Both.nil_inv h
      apply Eq_t.nil
  | _, .cons _ _ _, _, h => by
      obtain ⟨_, _, _, rfl, hbind, hboundary, _, hrest⟩ := Eq_t.Both.cons_inv h
      apply Eq_t.cons hbind.toEq_t hboundary hrest.toEq_t

/-- An ambient is well formed when it is a well-formed telescope over the empty
ambient. -/
def Ambient.Wf {Δ : C.Arity} (Ξ : Ambient Δ) : Prop :=
  Wf_t (.nil : Ambient 1) Ξ
