name = "HigherRankSyntax"
defaultTargets = ["HigherRankSyntax"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "HigherRankSyntax"

[[lean_lib]]
name = "ListCarrier"
srcDir = "examples"

[[lean_lib]]
name = "ListPrecedence"
srcDir = "examples"

[[lean_lib]]
name = "MagmaSignature"
srcDir = "examples/magma"

[[lean_lib]]
name = "MagmaTerm"
srcDir = "examples/magma"

[[lean_lib]]
name = "MagmaAdequacy"
srcDir = "examples/magma"

[[lean_lib]]
name = "MonoidEquations"
srcDir = "examples/monoid"

[[lean_lib]]
name = "DependentClassification"
srcDir = "examples/dependent"

[[lean_lib]]
name = "QuotientDependentClassification"
srcDir = "examples/dependent"

[[lean_lib]]
name = "NatSignature"
srcDir = "examples/nat"

[[lean_lib]]
name = "NatEquationalLogic"
srcDir = "examples/nat"
