import HigherRankSyntax.Equations.Presentation

/-!
# Equality generated by an equation presentation

`DerivEq E` is the least proof-irrelevant equality on raw expressions that
contains the schemas of `E`, is an equivalence relation, compares applications
argument by argument in their actual binding contexts, and is stable under
simultaneous substitution in both the expression and its fillers.

The relation is indexed by an arbitrary ambient arity so its application rule
does not require reassociating contexts.  The fixed prefix appears in the axiom
and substitution rules, where it protects the signature from substitution.
-/

variable {A : Type} {C : Carrier A} {S : C.Arity}

namespace Equations

/-- A structural, two-sided substitution congruence for fixed-prefix syntax. -/
structure SyntaxCongruence (C : Carrier A) (S : C.Arity) where
  Rel : {Ω : C.Arity} → {τ : C.Ty} → Expr Ω τ → Expr Ω τ → Prop
  refl {Ω : C.Arity} {τ : C.Ty} (e : Expr Ω τ) : Rel e e
  symm {Ω : C.Arity} {τ : C.Ty} {e e' : Expr Ω τ} :
    Rel e e' → Rel e' e
  trans {Ω : C.Arity} {τ : C.Ty} {e e' e'' : Expr Ω τ} :
    Rel e e' → Rel e' e'' → Rel e e''
  application {Ω Λ : C.Arity} {τ : C.Ty} (x : Ω ∋[τ] Λ)
      (args args' : Expr.Args Ω Λ) :
    (∀ {Δ : C.Arity} {υ : C.Ty} (i : Λ ∋[υ] Δ), Rel (args i) (args' i)) →
      Rel (.ap x args) (.ap x args')
  substitute {Γ Δ Φ : C.Arity} {τ : C.Ty}
      {e e' : STerm S Γ Φ τ} (σ θ : Subst Γ (S ⋈ Δ)) :
    Rel e e' →
    (∀ {Λ : C.Arity} {υ : C.Ty} (x : Γ ∋[υ] Λ), Rel (σ x) (θ x)) →
      Rel (Subst.act (Γ := S) σ Φ e) (Subst.act (Γ := S) θ Φ e')

namespace SyntaxCongruence

/-- A congruence contains an equation presentation when it relates every
declared schema. -/
def Contains (R : SyntaxCongruence C S) (E : EquationPresentation C S) : Prop :=
  ∀ {Γ Φ : C.Arity} {τ : C.Ty} {e e' : STerm S Γ Φ τ},
    E.axioms e e' → R.Rel e e'

end SyntaxCongruence

/-- Derivable equality generated by the schemas, equivalence rules,
application congruence, and two-sided substitution. -/
inductive DerivEq (E : EquationPresentation C S) :
    {Ω : C.Arity} → {τ : C.Ty} → Expr Ω τ → Expr Ω τ → Prop where
  | of_axiom {Γ Φ : C.Arity} {τ : C.Ty} {e e' : STerm S Γ Φ τ} :
      E.axioms e e' → DerivEq E e e'
  | refl {Ω : C.Arity} {τ : C.Ty} (e : Expr Ω τ) : DerivEq E e e
  | symm {Ω : C.Arity} {τ : C.Ty} {e e' : Expr Ω τ} :
      DerivEq E e e' → DerivEq E e' e
  | trans {Ω : C.Arity} {τ : C.Ty} {e e' e'' : Expr Ω τ} :
      DerivEq E e e' → DerivEq E e' e'' → DerivEq E e e''
  | application {Ω Λ : C.Arity} {τ : C.Ty} (x : Ω ∋[τ] Λ)
      (args args' : Expr.Args Ω Λ) :
      (∀ {Δ : C.Arity} {υ : C.Ty} (i : Λ ∋[υ] Δ),
        DerivEq E (args i) (args' i)) →
      DerivEq E (.ap x args) (.ap x args')
  | substitute {Γ Δ Φ : C.Arity} {τ : C.Ty}
      {e e' : STerm S Γ Φ τ} (σ θ : Subst Γ (S ⋈ Δ)) :
      DerivEq E e e' →
      (∀ {Λ : C.Arity} {υ : C.Ty} (x : Γ ∋[υ] Λ),
        DerivEq E (σ x) (θ x)) →
      DerivEq E (Subst.act (Γ := S) σ Φ e)
        (Subst.act (Γ := S) θ Φ e')

namespace DerivEq

/-- Derivable equality is a syntax congruence. -/
def congruence (E : EquationPresentation C S) : SyntaxCongruence C S where
  Rel := DerivEq E
  refl := .refl
  symm := .symm
  trans := .trans
  application := .application
  substitute := .substitute

/-- The derivable congruence contains every declared schema. -/
theorem congruence_contains (E : EquationPresentation C S) :
    (congruence E).Contains E :=
  fun h => .of_axiom h

/-- Derivable equality is contained in every syntax congruence containing the
declared schemas. -/
theorem least (E : EquationPresentation C S) (R : SyntaxCongruence C S)
    (hR : R.Contains E) {Ω : C.Arity} {τ : C.Ty} {e e' : Expr Ω τ} :
    DerivEq E e e' → R.Rel e e' := by
  intro h
  induction h with
  | of_axiom h => exact hR h
  | refl e => exact R.refl e
  | symm _ ih => exact R.symm ih
  | trans _ _ ih ih' => exact R.trans ih ih'
  | application x args args' _ ih => exact R.application x args args' ih
  | substitute σ θ _ _ ih ih' => exact R.substitute σ θ ih ih'

/-- Substitution stability with the same fillers on both sides. -/
theorem substitute_same (E : EquationPresentation C S)
    {Γ Δ Φ : C.Arity} {τ : C.Ty} {e e' : STerm S Γ Φ τ}
    (h : DerivEq E e e') (σ : Subst Γ (S ⋈ Δ)) :
    DerivEq E (Subst.act (Γ := S) σ Φ e)
      (Subst.act (Γ := S) σ Φ e') :=
  .substitute σ σ h (fun _ => .refl _)

/-- Pointwise-equivalent fillers act equivalently on a common expression. -/
theorem substitute_fillers (E : EquationPresentation C S)
    {Γ Δ Φ : C.Arity} {τ : C.Ty} (e : STerm S Γ Φ τ)
    (σ θ : Subst Γ (S ⋈ Δ))
    (h : ∀ {Λ : C.Arity} {υ : C.Ty} (x : Γ ∋[υ] Λ),
      DerivEq E (σ x) (θ x)) :
    DerivEq E (Subst.act (Γ := S) σ Φ e)
      (Subst.act (Γ := S) θ Φ e) :=
  .substitute σ θ (.refl e) h

/-- A renaming of metavariables, expressed as eta-substitution below the
fixed signature, preserves derivable equality. -/
theorem rename (E : EquationPresentation C S)
    {Γ Δ Φ : C.Arity} {τ : C.Ty} {e e' : STerm S Γ Φ τ}
    (h : DerivEq E e e') (ρ : Γ →ʳ Δ) :
    DerivEq E
      (Subst.act (Γ := S)
        (Subst.ofRenaming (fun ⦃_⦄ ⦃_⦄ x => C.inr (ρ x))) Φ e)
      (Subst.act (Γ := S)
        (Subst.ofRenaming (fun ⦃_⦄ ⦃_⦄ x => C.inr (ρ x))) Φ e') :=
  substitute_same E h _

/-- Every declared schema has all of its simultaneous substitution instances. -/
theorem axiom_instance (E : EquationPresentation C S)
    {Γ Δ Φ : C.Arity} {τ : C.Ty} {e e' : STerm S Γ Φ τ}
    (h : E.axioms e e') (σ : Subst Γ (S ⋈ Δ)) :
    DerivEq E (Subst.act (Γ := S) σ Φ e)
      (Subst.act (Γ := S) σ Φ e') :=
  substitute_same E (.of_axiom h) σ

end DerivEq

end Equations
