import HigherRankSyntax.Carrier

/-!
# Shapes and slots

The framework-level data on top of a `Carrier`.

* **Shapes.**  `Shape C` is the inductive type generated by the carrier's base shapes
  (`.base γ`) and one-step extension by an arity (`.ext Γ α`, notation `Γ ⋈ α`).

* **Slots.**  `Slot Γ` is inductively the slots of `Γ`, with one constructor per layer:
  `.base x` for a variable of the base shape, `.here i` for a binder introduced at this
  `ext` layer, `.there p` for a slot inherited from the shape below.

* **Slot arity.**  `Slot.arity` reads off the arity of a slot by recursion: a base slot
  uses the variable's `arity`, a `.here` binder uses the binder's `arity`, a `.there`
  slot inherits from the shape below.  The equations hold by `rfl`.
-/


/-- A shape over a carrier `C`: either a base shape, or a one-step extension `Γ ⋈ α`. -/
inductive Shape (C : Carrier) where
  /-- The base shape associated with `γ : C.BaseShape`. -/
  | base : (γ : C.BaseShape) → Shape C
  /-- Extension of a shape by all the binders of an arity. -/
  | ext  : (Γ : Shape C) → (α : C.Arity) → Shape C

/-- Action of an arity on a shape. -/
infixl:65 " ⋈ " => Shape.ext

/-- A slot of a shape: a variable of the base layer, a fresh binder of the topmost
extension, or a slot inherited from the shape below. -/
inductive Slot {C : Carrier} : Shape C → Type where
  /-- A variable of the base shape. -/
  | base  : {γ : C.BaseShape} → (x : C.Var γ) → Slot (.base γ)
  /-- A binder introduced by the topmost extension. -/
  | here  : {Γ : Shape C} → {α : C.Arity} → (i : C.Binder α) → Slot (Γ ⋈ α)
  /-- A slot inherited from the shape below the topmost extension. -/
  | there : {Γ : Shape C} → {α : C.Arity} → (p : Slot Γ) → Slot (Γ ⋈ α)

/-- The arity of a slot, by recursion on its constructors. -/
def Slot.arity {C : Carrier} {Γ : Shape C} : Slot Γ → C.Arity
  | .base x  => x.arity
  | .here i  => i.arity
  | .there p => p.arity

@[simp] theorem Slot.arity_base {C : Carrier} {γ : C.BaseShape} (x : C.Var γ) :
    (Slot.base (C := C) x).arity = x.arity := rfl

@[simp] theorem Slot.arity_here {C : Carrier} {Γ : Shape C} {α : C.Arity}
    (i : C.Binder α) : (Slot.here (Γ := Γ) i).arity = i.arity := rfl

@[simp] theorem Slot.arity_there {C : Carrier} {Γ : Shape C} {α : C.Arity}
    (p : Slot Γ) : (Slot.there (α := α) p).arity = p.arity := rfl

/-- Iterated extension of a shape by a list of arities, cons-as-snoc: the head of the list
is the outermost extension.  `Γ ⋈* (β :: rest) := (Γ ⋈* rest) ⋈ β` and `Γ ⋈* [] := Γ`. -/
def Shape.extList {C : Carrier} (Γ : Shape C) : List C.Arity → Shape C
  | []        => Γ
  | β :: rest => (Shape.extList Γ rest) ⋈ β

/-- Iterated extension of a shape by a list of arities. -/
infixl:67 " ⋈* " => Shape.extList

@[simp] theorem Shape.extList_nil {C : Carrier} (Γ : Shape C) : Γ ⋈* [] = Γ := rfl

@[simp] theorem Shape.extList_cons {C : Carrier} (Γ : Shape C) (β : C.Arity)
    (rest : List C.Arity) : Γ ⋈* (β :: rest) = (Γ ⋈* rest) ⋈ β := rfl

/-- Associativity of iterated extension w.r.t. list append: extending by `ys` then by
`xs` equals extending by `xs ++ ys`.  Reduces to `rfl` when `xs = []`. -/
theorem Shape.extList_append {C : Carrier} (Γ : Shape C) :
    ∀ (xs ys : List C.Arity), (Γ ⋈* ys) ⋈* xs = Γ ⋈* (xs ++ ys)
  | [],        _  => rfl
  | x :: xs',  ys => by
    show ((Γ ⋈* ys) ⋈* xs') ⋈ x = (Γ ⋈* (xs' ++ ys)) ⋈ x
    rw [Shape.extList_append Γ xs' ys]

