import HigherRankSyntax.Carrier

/-!
# Shapes and slots

The framework-level data on top of a `Carrier`.

* **Shapes.**  `Shape C` is the inductive type generated by the carrier's base shapes
  (`.base γ`) and one-step extension by an arity (`.ext Γ α`, notation `Γ ⋈ α`).

* **Slots.**  `Slot Γ` is inductively the slots of `Γ`, with one constructor per layer:
  `.base x` for a variable of the base shape, `.here i` for a binder introduced at this
  `ext` layer, `.there p` for a slot inherited from the shape below.

* **Slot arity.**  `Slot.arity` reads off the arity of a slot by recursion: a base slot
  uses the variable's `arity`, a `.here` binder uses the binder's `arity`, a `.there`
  slot inherits from the shape below.  The equations hold by `rfl`.
-/


/-- A shape over a carrier `C`: either a base shape, or a one-step extension `Γ ⋈ α`. -/
inductive Shape (C : Carrier) where
  /-- The base shape associated with `γ : C.BaseShape`. -/
  | base : (γ : C.BaseShape) → Shape C
  /-- Extension of a shape by all the binders of an arity. -/
  | ext  : (Γ : Shape C) → (α : C.Arity) → Shape C

/-- Action of an arity on a shape. -/
infixl:65 " ⋈ " => Shape.ext

/-- A slot of a shape with its arity tracked as a type index: a variable of the base
layer (`.base x` at `x.arity`), a fresh binder of the topmost extension (`.here i` at
`i.arity`), or a slot inherited from the shape below (`.there p` at the same arity as
`p`). -/
inductive SlotAt {C : Carrier} : Shape C → C.Arity → Type where
  /-- A variable of the base shape at its variable's arity. -/
  | base  : {γ : C.BaseShape} → (x : C.Var γ) → SlotAt (.base γ) x.arity
  /-- A binder introduced by the topmost extension at its binder's arity. -/
  | here  : {Γ : Shape C} → {α : C.Arity} → (i : C.Binder α) → SlotAt (Γ ⋈ α) i.arity
  /-- A slot inherited from the shape below the topmost extension, at the same arity. -/
  | there : {Γ : Shape C} → {β α : C.Arity} → SlotAt Γ α → SlotAt (Γ ⋈ β) α

/-- `Γ ∋ α` is the type of slots of `Γ` at arity `α`. -/
notation:35 Γ " ∋ " α => SlotAt Γ α

/-- Extract the arity index from a slot. -/
@[reducible]
def SlotAt.arity {C : Carrier} {Γ : Shape C} {α : C.Arity} (_ : Γ ∋ α) : C.Arity := α

/-- Iterated extension of a shape by a list of arities, cons-as-snoc: the head of the list
is the outermost extension.  `Γ ⋈* (β :: rest) := (Γ ⋈* rest) ⋈ β` and `Γ ⋈* [] := Γ`. -/
def Shape.extList {C : Carrier} (Γ : Shape C) : List C.Arity → Shape C
  | []        => Γ
  | β :: rest => (Shape.extList Γ rest) ⋈ β

/-- Iterated extension of a shape by a list of arities. -/
infixl:67 " ⋈* " => Shape.extList

@[simp] theorem Shape.extList_nil {C : Carrier} (Γ : Shape C) : Γ ⋈* [] = Γ := rfl

@[simp] theorem Shape.extList_cons {C : Carrier} (Γ : Shape C) (β : C.Arity)
    (rest : List C.Arity) : Γ ⋈* (β :: rest) = (Γ ⋈* rest) ⋈ β := rfl

/-- Associativity of iterated extension w.r.t. list append: extending by `ys` then by
`xs` equals extending by `xs ++ ys`.  Reduces to `rfl` when `xs = []`. -/
theorem Shape.extList_append {C : Carrier} (Γ : Shape C) :
    ∀ (xs ys : List C.Arity), (Γ ⋈* ys) ⋈* xs = Γ ⋈* (xs ++ ys)
  | [],        _  => rfl
  | x :: xs',  ys => by
    show ((Γ ⋈* ys) ⋈* xs') ⋈ x = (Γ ⋈* (xs' ++ ys)) ⋈ x
    rw [Shape.extList_append Γ xs' ys]

